// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAosYHyCQk0EgYvZLu0YrrFL3hpiTixdkY',
    appId: '1:214372646360:web:0be115a45c9b3a2bb406ad',
    messagingSenderId: '214372646360',
    projectId: 'project3-1071b',
    authDomain: 'project3-1071b.firebaseapp.com',
    storageBucket: 'project3-1071b.appspot.com',
    measurementId: 'G-G0DLB8G9B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1BNxJ3-oXw7Qv9XrWbxv1ItzeQzdjiak',
    appId: '1:214372646360:android:38ea5ab49bd0b74eb406ad',
    messagingSenderId: '214372646360',
    projectId: 'project3-1071b',
    storageBucket: 'project3-1071b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGgbbs6bwxPw8DNc5ye7fh7jeFivdJqA',
    appId: '1:214372646360:ios:6e85cc280be65b4fb406ad',
    messagingSenderId: '214372646360',
    projectId: 'project3-1071b',
    storageBucket: 'project3-1071b.appspot.com',
    iosClientId: '214372646360-kjpq10df4jb54t0nmlrvktfigjnal15b.apps.googleusercontent.com',
    iosBundleId: 'com.example.labor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGgbbs6bwxPw8DNc5ye7fh7jeFivdJqA',
    appId: '1:214372646360:ios:4323d7368efbc11ab406ad',
    messagingSenderId: '214372646360',
    projectId: 'project3-1071b',
    storageBucket: 'project3-1071b.appspot.com',
    iosClientId: '214372646360-2s51uf6db9qmujhcm761e63odbgivhov.apps.googleusercontent.com',
    iosBundleId: 'com.example.labor.RunnerTests',
  );
}
